/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cac2_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class detail extends javax.swing.JFrame {

    /**
     * Creates new form detail
     */
    String a,b,d,k,f,g,r,z;
    int x;
    vegge v=new vegge();
    summer s=new summer();
    chicken c=new chicken();
    login i=new login();
     String n=i.j;
     Connection con;
    Statement stmt;
    String sql;
    public detail() {
        initComponents();
          try{
                Class.forName("com.mysql.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                 stmt=con.createStatement();
                sql="select * from pizzadetail where Username='"+n+"'";
                ResultSet rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                    k=rs.getString("Pname");
                    f=rs.getString("Size");
                    g=rs.getString("Quantity");
                    r=rs.getString("Prize");
                    t1.setText(k);
                    t7.setText(f);
                    t2.setText(g);
                    t4.setText(r);
                }
                 sql="select * from register where UserName='"+n+"'";
                 rs=stmt.executeQuery(sql);
                while(rs.next())
                {
                    k=rs.getString("Address");
                    t3.setText(k);
                }
                rs.close();
            }
            catch(Exception e1){
               
            }
        a=String.valueOf(v.num);
        b=String.valueOf(s.num);
        d=String.valueOf(c.num);
        if(a.equals("0"))
        {
            if(b.equals("0"))
            {
                if(d.equals("1"))
                {
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/loaded.jpg")));
                }
                else if(d.equals("2"))
                {
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/periperi.jpg")));
                }
                else 
                {
                    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/barbeque.jpg")));
                }
            }
             else
                {
                    if(b.equals("4"))
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/veg.jpg")));
                    }
                    else if(b.equals("5"))
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/non.jpg")));
                    }
                    else 
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/che.jpg")));
                    }
                }
        }
         else
                {
                    if(a.equals("7"))
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/vegge1.jpg")));
                    }
                    else if(a.equals("8"))
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/vegge2.jpg")));
                    }
                    else 
                    {
                        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/vegge3.jpg")));
                    }
                }
        t5.setText("Cash On Delivery");
        l6.setText(n);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        l10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t3 = new javax.swing.JTextArea();
        l6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0.0f,0.0f,0.0f,0.5f));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 62)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ORDER DETAIL");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        jLabel4.setPreferredSize(new java.awt.Dimension(180, 140));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 230, 190));

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel5.setText("Size :");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        t5.setEditable(false);
        t5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t5.setForeground(new java.awt.Color(51, 51, 51));
        t5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 140, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel6.setText("Payment :");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setText("Name :");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel8.setText("Quantity :");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel9.setText("Address :");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        t2.setEditable(false);
        t2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t2.setForeground(new java.awt.Color(51, 51, 51));
        t2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 140, -1));

        t7.setEditable(false);
        t7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t7.setForeground(new java.awt.Color(51, 51, 51));
        t7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t7.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 140, -1));

        jButton1.setBackground(java.awt.Color.magenta);
        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BUY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 110, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel10.setText("Prize :");
        jLabel10.setToolTipText("");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t4.setForeground(new java.awt.Color(51, 51, 51));
        t4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 140, -1));

        t1.setEditable(false);
        t1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t1.setForeground(new java.awt.Color(51, 51, 51));
        t1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        t1.setSelectionColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, -1));

        l10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        l10.setForeground(new java.awt.Color(204, 204, 255));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 260, 30));

        t3.setEditable(false);
        t3.setColumns(20);
        t3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        t3.setForeground(new java.awt.Color(51, 51, 51));
        t3.setRows(5);
        jScrollPane1.setViewportView(t3);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, 50));

        l6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 80, 20));

        l1.setBackground(new java.awt.Color(1f,1f,1f,0.5f));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/vegge.jpg"))); // NOI18N
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        setSize(new java.awt.Dimension(620, 410));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new address().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new thankyou().setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l6;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
