/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cac2_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static cac2_project.vegge.name;

/**
 *
 * @author Admin
 */
public class summer extends javax.swing.JFrame {

    /**
     * Creates new form summer
     */
         
    int a=499;
    int b=599;
    int c=699;
    int d,a1=0;
    static int num;
    login l=new login();
    String e="RS.";
    String f=l.j;
     static String name;
    public summer() {
        initComponents();
          r1.setSelected(true);
        r3.setSelected(true);
        r5.setSelected(true);
        r7.setSelected(true);
        r10.setSelected(true);
        r13.setSelected(true);
        jLabel4.setText(e+a);
        jLabel5.setText(e+b);
        jLabel6.setText(e+c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r9 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        r3 = new javax.swing.JRadioButton();
        r4 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        r5 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        r15 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0.0f,0.0f,0.0f,0.6f));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 62)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SUMMER LOVER");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 60));

        jPanel2.setBackground(new java.awt.Color(1f,1f,1f,0.5f));
        jPanel2.setDoubleBuffered(false);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/veg.jpg"))); // NOI18N

        l6.setBackground(new java.awt.Color(1f,1f,1f,0.5f));
        l6.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l6.setForeground(java.awt.Color.magenta);
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("VEG SPECIAL");

        jButton1.setBackground(java.awt.Color.magenta);
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.setFocusable(false);
        jButton1.setHideActionText(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.magenta);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setInheritsPopupMenu(false);
        jLabel4.setOpaque(true);

        r1.setBackground(java.awt.Color.white);
        buttonGroup1.add(r1);
        r1.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r1.setForeground(java.awt.Color.magenta);
        r1.setText("MEDIUM ");
        r1.setFocusPainted(false);
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        r2.setBackground(java.awt.Color.white);
        buttonGroup1.add(r2);
        r2.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r2.setForeground(java.awt.Color.magenta);
        r2.setText("LARGE");
        r2.setContentAreaFilled(false);
        r2.setOpaque(true);
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        r7.setBackground(java.awt.Color.white);
        buttonGroup2.add(r7);
        r7.setForeground(java.awt.Color.magenta);
        r7.setText("1");
        r7.setContentAreaFilled(false);
        r7.setOpaque(true);
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });

        r8.setBackground(java.awt.Color.white);
        buttonGroup2.add(r8);
        r8.setForeground(java.awt.Color.magenta);
        r8.setText("2");
        r8.setContentAreaFilled(false);
        r8.setOpaque(true);
        r8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r8ActionPerformed(evt);
            }
        });

        r9.setBackground(java.awt.Color.white);
        buttonGroup2.add(r9);
        r9.setForeground(java.awt.Color.magenta);
        r9.setText("3");
        r9.setContentAreaFilled(false);
        r9.setOpaque(true);
        r9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l3)
                    .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(r7)
                        .addGap(18, 18, 18)
                        .addComponent(r8)
                        .addGap(18, 18, 18)
                        .addComponent(r9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(r1)
                        .addGap(18, 18, 18)
                        .addComponent(r2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(l6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r1)
                    .addComponent(r2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r7)
                    .addComponent(r8)
                    .addComponent(r9))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 310));

        jPanel3.setBackground(new java.awt.Color(1f,1f,1f,0.5f));
        jPanel3.setDoubleBuffered(false);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/non.jpg"))); // NOI18N

        l7.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l7.setForeground(java.awt.Color.magenta);
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("NON-VEG SPECIAL");

        r3.setBackground(java.awt.Color.white);
        buttonGroup3.add(r3);
        r3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r3.setForeground(java.awt.Color.magenta);
        r3.setText("MEDIUM ");
        r3.setContentAreaFilled(false);
        r3.setOpaque(true);
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        r4.setBackground(java.awt.Color.white);
        buttonGroup3.add(r4);
        r4.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r4.setForeground(java.awt.Color.magenta);
        r4.setText("LARGE");
        r4.setContentAreaFilled(false);
        r4.setOpaque(true);
        r4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r4ActionPerformed(evt);
            }
        });

        r11.setBackground(java.awt.Color.white);
        buttonGroup4.add(r11);
        r11.setForeground(java.awt.Color.magenta);
        r11.setText("2");
        r11.setContentAreaFilled(false);
        r11.setOpaque(true);
        r11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r11ActionPerformed(evt);
            }
        });

        r10.setBackground(java.awt.Color.white);
        buttonGroup4.add(r10);
        r10.setForeground(java.awt.Color.magenta);
        r10.setText("1");
        r10.setContentAreaFilled(false);
        r10.setOpaque(true);
        r10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r10ActionPerformed(evt);
            }
        });

        r12.setBackground(java.awt.Color.white);
        buttonGroup4.add(r12);
        r12.setForeground(java.awt.Color.magenta);
        r12.setText("3");
        r12.setContentAreaFilled(false);
        r12.setOpaque(true);
        r12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r12ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.magenta);
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ADD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.magenta);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setFocusable(false);
        jLabel5.setInheritsPopupMenu(false);
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l4)
            .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(r3)
                .addGap(18, 18, 18)
                .addComponent(r4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(r10)
                .addGap(18, 18, 18)
                .addComponent(r11)
                .addGap(18, 18, 18)
                .addComponent(r12))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r3)
                    .addComponent(r4))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r10)
                    .addComponent(r11)
                    .addComponent(r12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 80, 180, 310));

        jPanel4.setBackground(new java.awt.Color(1f,1f,1f,0.5f));

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/che.jpg"))); // NOI18N

        l8.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        l8.setForeground(java.awt.Color.magenta);
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("CHEESEE SPECIAL");

        r5.setBackground(java.awt.Color.white);
        buttonGroup5.add(r5);
        r5.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r5.setForeground(java.awt.Color.magenta);
        r5.setText("MEDIUM ");
        r5.setContentAreaFilled(false);
        r5.setOpaque(true);
        r5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r5ActionPerformed(evt);
            }
        });

        r6.setBackground(java.awt.Color.white);
        buttonGroup5.add(r6);
        r6.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        r6.setForeground(java.awt.Color.magenta);
        r6.setText("LARGE");
        r6.setContentAreaFilled(false);
        r6.setOpaque(true);
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });

        r13.setBackground(java.awt.Color.white);
        buttonGroup6.add(r13);
        r13.setForeground(java.awt.Color.magenta);
        r13.setText("1");
        r13.setContentAreaFilled(false);
        r13.setOpaque(true);
        r13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r13ActionPerformed(evt);
            }
        });

        r15.setBackground(java.awt.Color.white);
        buttonGroup6.add(r15);
        r15.setForeground(java.awt.Color.magenta);
        r15.setText("3");
        r15.setContentAreaFilled(false);
        r15.setOpaque(true);
        r15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r15ActionPerformed(evt);
            }
        });

        r14.setBackground(java.awt.Color.white);
        buttonGroup6.add(r14);
        r14.setForeground(java.awt.Color.magenta);
        r14.setText("2");
        r14.setContentAreaFilled(false);
        r14.setOpaque(true);
        r14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r14ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.magenta);
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.magenta);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setFocusable(false);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l5)
            .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(r5)
                .addGap(18, 18, 18)
                .addComponent(r6))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(r13)
                .addGap(18, 18, 18)
                .addComponent(r14)
                .addGap(18, 18, 18)
                .addComponent(r15))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(l8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r5)
                    .addComponent(r6))
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r13)
                    .addComponent(r14)
                    .addComponent(r15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 180, 310));

        l1.setBackground(new java.awt.Color(1f,1f,1f,0.5f));
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cac2_project/vegge.jpg"))); // NOI18N
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        setSize(new java.awt.Dimension(626, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new order().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         num=4;
         name="S.Veg Special";
         String na;
        int q;
        if(r1.isSelected())
        {
            na="Medium";
        }
        else
        {
            na="Large";
        }
        if(r7.isSelected())
        {
            q=1;
             if(r1.isSelected())
            {
                d=499;
            }
            else
            {
                d=899;
            }
        }
        else if(r8.isSelected())
        {
            q=2;
        }
        else
        {
            q=3;
        }
        /*try{
              Class.forName("com.mysql.jdbc.Driver");
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
              Statement stmt=con.createStatement();
              String sql="select * from pizzadetail where Username='"+f+"'";
              ResultSet rs=stmt.executeQuery(sql);
               if(rs.next() == false)
               {
                   throw Exception();
               }
                rs.close();
               sql="update pizzadetail set Pname='"+name+"',Size='"+na+"',Quantity='"+q+"',Prize='"+d+"' where Username='"+f+"'";
               stmt.executeUpdate(sql);  
            
        }
        catch(Exception e2)
        {*/
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                Statement stmt=con.createStatement();
                String sql1="select * from pizzadetail where Username='"+f+"'";
                ResultSet rs=stmt.executeQuery(sql1);
                while(rs.next())
                {
                    a1=rs.getInt("id");
                }
                String sql="insert into pizzadetail(id,Username,Pname,Size,Quantity,Prize,img)"+"values('"+(a1+1)+"','"+f+"','"+name+"','"+na+"','"+q+"','"+d+"','veg.jpg')";
                stmt.executeUpdate(sql);
            }
            catch(Exception e1){
                JOptionPane.showMessageDialog(null, e1);
            }
       // }
        new cart().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        if(r7.isSelected())
        {
            d=a;
            jLabel4.setText(e+d);
        }
        else if(r8.isSelected())
        {
            d=2*(a);
            jLabel4.setText(e+d);
        }
        else
        {
            d=3*(a);
            jLabel4.setText(e+d);
        }
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        if(r7.isSelected())
        {
            d=a+a+1-100;
            jLabel4.setText(e+d);
        }
        else if(r8.isSelected())
        {
            d=2*(a+a+1-100);
            jLabel4.setText(e+d);
        }
        else
        {
            d=3*(a+a+1-100);
            jLabel4.setText(e+d);
        }
    }//GEN-LAST:event_r2ActionPerformed

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        if(r1.isSelected())
        {
            d=a;
            jLabel4.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=(a+a+1-100);
            jLabel4.setText(e+d);
        }
    }//GEN-LAST:event_r7ActionPerformed

    private void r8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r8ActionPerformed
        if(r1.isSelected())
        {
            d=2*a;
            jLabel4.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=2*(a+a+1-100);
            jLabel4.setText(e+d);
        }
    }//GEN-LAST:event_r8ActionPerformed

    private void r9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r9ActionPerformed
        if(r1.isSelected())
        {
            d=3*a;
            jLabel4.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=3*(a+a+1-100);
            jLabel4.setText(e+d);
        }
    }//GEN-LAST:event_r9ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        if(r10.isSelected())
        {
            d=b;
            jLabel5.setText(e+d);
        }
        else if(r11.isSelected())
        {
            d=2*(b);
            jLabel5.setText(e+d);
        }
        else
        {
            d=3*(b);
            jLabel5.setText(e+d);
        }
    }//GEN-LAST:event_r3ActionPerformed

    private void r4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r4ActionPerformed
        if(r10.isSelected())
        {
            d=b+b+1-100;
            jLabel5.setText(e+d);
        }
        else if(r11.isSelected())
        {
            d=2*(b+b+1-100);
            jLabel5.setText(e+d);
        }
        else
        {
            d=3*(b+b+1-100);
            jLabel5.setText(e+d);
        }
    }//GEN-LAST:event_r4ActionPerformed

    private void r11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r11ActionPerformed
        if(r1.isSelected())
        {
            d=2*b;
            jLabel5.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=2*(b+b+1-100);
            jLabel5.setText(e+d);
        }
    }//GEN-LAST:event_r11ActionPerformed

    private void r10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r10ActionPerformed
        if(r1.isSelected())
        {
            d=b;
            jLabel5.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=(b+b+1-100);
            jLabel5.setText(e+d);
        }
    }//GEN-LAST:event_r10ActionPerformed

    private void r12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r12ActionPerformed
        if(r1.isSelected())
        {
            d=3*b;
            jLabel5.setText(e+d);
        }
        else if(r2.isSelected())
        {
            d=3*(b+b+1-100);
            jLabel5.setText(e+d);
        }
    }//GEN-LAST:event_r12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            num=5;
            name="S.Non-Veg Special";
            String na;
        int q;
        if(r3.isSelected())
        {
            na="Medium";
        }
        else
        {
            na="Large";
        }
        if(r10.isSelected())
        {
            q=1;
             if(r3.isSelected())
            {
                d=599;
            }
            else
            {
                d=1099;
            }
        }
        else if(r11.isSelected())
        {
            q=2;
        }
        else
        {
            q=3;
        }
        /*try{
              Class.forName("com.mysql.jdbc.Driver");
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
              Statement stmt=con.createStatement();
              String sql="select * from pizzadetail where Username='"+f+"'";
              ResultSet rs=stmt.executeQuery(sql);
            if(rs.next() == false)
               {
                   throw Exception();
               }
                rs.close();
               sql="update pizzadetail set Pname='"+name+"',Size='"+na+"',Quantity='"+q+"',Prize='"+d+"' where Username='"+f+"'";
               stmt.executeUpdate(sql);  
            
        }
        catch(Exception e2)
        {*/
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                Statement stmt=con.createStatement();
                 String sql1="select * from pizzadetail where Username='"+f+"'";
                ResultSet rs=stmt.executeQuery(sql1);
                while(rs.next())
                {
                    a1=rs.getInt("id");
                }
                String sql="insert into pizzadetail(id,Username,Pname,Size,Quantity,Prize,img)"+"values('"+(a1+1)+"','"+f+"','"+name+"','"+na+"','"+q+"','"+d+"','non.jpg')";
                stmt.executeUpdate(sql);
            }
            catch(Exception e1){
                JOptionPane.showMessageDialog(null, e1);
            } 
       // }
        new cart().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void r5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r5ActionPerformed
        if(r13.isSelected())
        {
            d=c;
            jLabel6.setText(e+d);
        }
        else if(r14.isSelected())
        {
            d=2*(c);
            jLabel6.setText(e+d);
        }
        else
        {
            d=3*(c);
            jLabel6.setText(e+d);
        }
    }//GEN-LAST:event_r5ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        if(r13.isSelected())
        {
            d=c+c+1-100;
            jLabel6.setText(e+d);
        }
        else if(r14.isSelected())
        {
            d=2*(c+c+1-100);
            jLabel6.setText(e+d);
        }
        else
        {
            d=3*(c+c+1-100);
            jLabel6.setText(e+d);
        }
    }//GEN-LAST:event_r6ActionPerformed

    private void r13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r13ActionPerformed
        if(r5.isSelected())
        {
            d=c;
            jLabel6.setText(e+d);
        }
        else if(r6.isSelected())
        {
            d=(c+c+1-100);
            jLabel6.setText(e+d);
        }
    }//GEN-LAST:event_r13ActionPerformed

    private void r15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r15ActionPerformed
        if(r5.isSelected())
        {
            d=3*c;
            jLabel6.setText(e+d);
        }
        else if(r6.isSelected())
        {
            d=3*(c+c+1-100);
            jLabel6.setText(e+d);
        }
    }//GEN-LAST:event_r15ActionPerformed

    private void r14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r14ActionPerformed
        if(r5.isSelected())
        {
            d=2*c;
            jLabel6.setText(e+d);
        }
        else if(r6.isSelected())
        {
            d=2*(c+c+1-100);
            jLabel6.setText(e+d);
        }
    }//GEN-LAST:event_r14ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            num=6;
            name="S.Cheesee Special";
            String na;
        int q;
        if(r5.isSelected())
        {
            na="Medium";
        }
        else
        {
            na="Large";
        }
        if(r13.isSelected())
        {
            q=1;
             if(r5.isSelected())
            {
                d=699;
            }
            else
            {
                d=1299;
            }
        }
        else if(r14.isSelected())
        {
            q=2;
        }
        else
        {
            q=3;
        }
        /*try{
              Class.forName("com.mysql.jdbc.Driver");
              Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
              Statement stmt=con.createStatement();
              String sql="select * from pizzadetail where Username='"+f+"'";
              ResultSet rs=stmt.executeQuery(sql);
              if(rs.next() == false)
               {
                   throw Exception();
               }
                rs.close();
               sql="update pizzadetail set Pname='"+name+"',Size='"+na+"',Quantity='"+q+"',Prize='"+d+"' where Username='"+f+"'";
               stmt.executeUpdate(sql);  
            
        }
        catch(Exception e2)
        {*/
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/student","root","");
                Statement stmt=con.createStatement();
                String sql1="select * from pizzadetail where Username='"+f+"'";
                ResultSet rs=stmt.executeQuery(sql1);
                while(rs.next())
                {
                    a1=rs.getInt("id");
                }
                String sql="insert into pizzadetail(id,Username,Pname,Size,Quantity,Prize,img)"+"values('"+(a1+1)+"','"+f+"','"+name+"','"+na+"','"+q+"','"+d+"','che.jpg')";
                stmt.executeUpdate(sql);
            }
            catch(Exception e1){
                JOptionPane.showMessageDialog(null, e1);
            } 
        //}
        new cart().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(summer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(summer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(summer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(summer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new summer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r15;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables

    private Exception Exception() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
